{% set version = "0.1.5" %}
package:
  name: sphinxcontrib-autoprogram
  version: {{ version }}

source:
  fn: sphinxcontrib-autoprogram-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinxcontrib-autoprogram/sphinxcontrib-autoprogram-{{ version }}.tar.gz
  sha256: 7ec6bdf235b491dc693d1a72fb7f9f734db69e29b81333435efb41f09f9bbeef

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.2
    - six

  run:
    - python
    - sphinx >=1.2
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-Clause
  summary: 'Documenting CLI programs'

extra:
  recipe-maintainers:
    - asmeurer
