{% set version = "0.1.7" %}
package:
  name: sphinxcontrib-autoprogram
  version: {{ version }}

source:
  fn: sphinxcontrib-autoprogram-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinxcontrib-autoprogram/sphinxcontrib-autoprogram-{{ version }}.tar.gz
  sha256: bc642e3f2817a7539f306e021697f72b225bea5ad23b30dc14a7b9d1408d1f1a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - sphinx >=1.2
    - six

  run:
    - python
    - sphinx >=1.2
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-Clause
  license_file: LICENSE
  summary: Documenting CLI programs

extra:
  recipe-maintainers:
    - asmeurer
