{% set version = "0.1.9" %}
package:
  name: sphinxcontrib-autoprogram
  version: {{ version }}

source:
  fn: sphinxcontrib-autoprogram-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinxcontrib-autoprogram/sphinxcontrib-autoprogram-{{ version }}.tar.gz
  sha256: 219655507fadca29b3062b5d86c37d94db48f03bde4b58d61526872bf72f57cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - sphinx >=1.2
    - six

  run:
    - python
    - sphinx >=1.2
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Documenting CLI programs'

extra:
  recipe-maintainers:
    - asmeurer
