{% set version = "0.1.4" %}
package:
  name: sphinxcontrib-autoprogram
  version: {{ version }}

source:
  fn: sphinxcontrib-autoprogram-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/sphinxcontrib-autoprogram/sphinxcontrib-autoprogram-{{ version }}.tar.gz
  sha256: 7081d1b72c1652e6aa93d05d9bb39576bebd5fa3358b28ad3010ef9dcc5eed4b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.2
    - six

  run:
    - python
    - sphinx >=1.2
    - six

test:
  imports:
    - sphinxcontrib

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-Clause
  summary: 'Documenting CLI programs'

extra:
  recipe-maintainers:
    - asmeurer
