travis:
  secure:
    BINSTAR_TOKEN: If3Yi8VxkuM/AGj5GbRpn4W35VSnstkVxz5gyPv3Ol8KRQMS9HOWXeCkvgcSUiSrRsg2/FUkPJ6WxfxmOjutLsN6vb0u4YpxEAfL174lQQ69WziixUdunSu1aA47DU2p+zBol9vrJoHltlMCms9T0rNYLXAkmkBk1YREGJ+imoRq+hU8bRnChGIokpjQrJMiSZB1fynQMWjER7XT6+IiSaRuXb5R7W8eRtyM9+dd1XOElOx1ayiOegA/9ZWY984No/vOXVxD3SF+klrivkbF4nI+g+txCqePJ2b6dhJY7NRtzPkfE/pAW6EUAojGTr88fhbd8wRyoCZDFOr59onAGDrJMA1FUKZJOeetctO2GRjagAGA+MTPwNHj3784tungtsr9Rg2EIuruJbvYsMYNvhdKdVAUQsDBr5NXFjNbUjiTklXHDxJyHipUo9dqp5NPc98AFe1QpDwdHK9/uCKBMqux0vW6y8Wzx8zCVrrGTLwHiUuCPNsHgNmof3oPLXJ/XafYiVF6jnil8tlp7wvH2t8bsSV3/mC1oKPoxtc8Wn5ImdY7QXT0nDEj19eEPIkSnh2CVzHleEw4bXSlErxOQSD96thm0qUCQwZhSxPsItkw5oHQLyn58hU7vylBAdMZOgvUE1rHSynoFMCxRvWLg1bzVdepWTEofux8bSe2TQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
