travis:
  secure:
    BINSTAR_TOKEN: JfiytWkvzn5unbH4yvxqkcePN5kZjuDJAyD+LTZhac43fY44wO+CDaAXNK5mmS/SkySWN/ihT6yBJM7UxRpsA30vYif3XO6QlpqaIHi58Otj6SW1wBNuuN41yPZn3eNF0sRBpfpcL2xQK7zTb9zmjGZNaCAEX6FtkO6bbK5cAmBBnYY4A1eO7rdOSNXDtONhU0DGxEdrpCl/6E4SeTTiPGXo5DBJhPaf0B2xpD8tcbnHpooKY21ezfSY/o3Zn4APjinpV0D+RjhKKhRQb8HinDYG2Knwc2NimDcBbeKQHmvOXqfyJOe+q0uHzOmi53lC/e+ULKe/iqEy1BnXahjvS5skr32oO/SF8BbJC+rpJkKVWjTK6EWccVIdogfT1wWYmJN0vHkfl2W7tecQIjYrULSefmvreCBb0pObd0VgixpsC5oo3O0NUp7AdQJnsmkLioHgxVSxHz2RKYPhFJZ2Wx9Cvrp6SsozmEX5ylkyaQMcwk2LgIv68152uQzzUMCcUbPp8WZUbb7ObpIdYHQiw0MNaT1WuP2HPojPUDRbQZJ92Gc2pkSiUCxjWN4VCtirsBO3Ee3GyGlSZddMJWf4nkHFfSfJ4UAIUYLcktFCiAk0tE9k4rtRfltpjmVmsOCymhKOeR4D7VqSvLQEZhWY6roalIZ0EsNFD0Vq66caVZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
